
variable "image_os" {
  type    = string
  default = "alpine:latest"
}

source "docker" "autogenerated_1" {
  commit = true
  image  = "${var.image_os}"
}

build {
  sources = ["source.docker.autogenerated_1"]

  provisioner "shell" {
    inline       = ["echo THIS IS NEEDED!!! Only doing this to add a pause before file transfers"]
    pause_after  = "3s"
    pause_before = "3s"
  }

  provisioner "file" {
    destination = "/tmp/welcome.txt"
    source      = "./install-files/welcome.txt"
  }

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E {{ .Path }}"
    pause_before    = "4s"
    scripts         = ["./install-scripts/update-upgrade-system.sh", "./install-scripts/add-user-jeff.sh", "./install-scripts/move-welcome-file-to-jeff.sh", "./install-scripts/install-packages.sh"]
  }

}
